# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [1]:

import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [25]:
# a = 
a = pd.Series([100,200,300,400])

Print a, and data type

In [26]:
print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.Series'>

Using indexing access the element 300 from the series a.

In [27]:
a[2]

np.int64(300)

What are the values of index for series a?

In [28]:

a.index

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [29]:

a.index = ['a', 'b', 'c','d']
a

a    100
b    200
c    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [30]:
a['d']

np.int64(400)

Sort the values wrt to the index and print it

In [31]:

a_sorted = a.sort_index()
print(a_sorted)

a    100
b    200
c    300
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [32]:
b = pd.Series([800,450,100],index=['e','f','g'])
b

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [33]:
# a =
a = pd.concat([a,b])

In [34]:
#print a again after appending b into it

print(a)

a    100
b    200
c    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [35]:
# a = 
a = a.sort_values(ascending=False)

In [36]:
print(a.index)

Index(['e', 'f', 'd', 'c', 'b', 'a', 'g'], dtype='str')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [37]:
# df = 
df = pd.DataFrame(a)

In [38]:
df

     0
e  800
f  450
d  400
c  300
b  200
a  100
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [40]:

df.shape

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [41]:
# yep its same as the series.
df.index

Index(['e', 'f', 'd', 'c', 'b', 'a', 'g'], dtype='str')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [45]:

# head() --> head will return first five row the data
# tail() --> tail will return last five row the data
df.head()

     0
e  800
f  450
d  400
c  300
b  200

In [46]:
df.tail()

     0
d  400
c  300
b  200
a  100
g  100

Rename the column of the dataframe as 'points'

In [47]:

df.columns = ['points']

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [53]:
#Create fruits array

fruits_choice = pd.Series(['Orange', 'Mango', 'Apple'])
fruits_array = np.random.choice(fruits_choice, 7)
fruits_array

array(['Orange', 'Apple', 'Mango', 'Orange', 'Mango', 'Apple', 'Mango'],
      dtype=object)

In [55]:
#Create series fruits out of fruits array

fruits = pd.Series(fruits_array)
fruits

0    Orange
1     Apple
2     Mango
3    Orange
4     Mango
5     Apple
6     Mango
dtype: str

Change the index of fruits to the index of dataframe df

In [57]:


fruits.index = df.index
fruits

e    Orange
f     Apple
d     Mango
c    Orange
b     Mango
a     Apple
g     Mango
dtype: str

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [59]:
df['fruits'] = fruits

In [60]:

df.head()

   points  fruits
e     800  Orange
f     450   Apple
d     400   Mango
c     300  Orange
b     200   Mango

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [62]:
d1 = pd.DataFrame({
    'city':['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
    'Temperature': [15,22,20,26,-2]
})

Print(d1)

In [63]:

print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [64]:
d1.shape

(5, 2)

Set city = d1['city']

In [65]:


city = d1['city']

print city <br>
What is the type of city.

In [66]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: str
<class 'pandas.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [68]:
d2 = pd.DataFrame({
    'city':['Bengaluru', 'Coimbatore', 'Srirangam', 'Pondicheery'],
    'Temperature' : [24,35,36,39]
})

print the shape of this dataframe

In [70]:
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [73]:
# d3 = 

d3 = pd.concat([d1,d2])
d3

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengaluru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicheery           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [76]:
d3[d3['Temperature'] <= 20]

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [78]:

d3[d3['Temperature'] >= 35]

          city  Temperature
1   Coimbatore           35
2    Srirangam           36
3  Pondicheery           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not. 
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [79]:
# write function here
def is_ut(x):
    return x in ['chandigarh', 'Pondicheery', 'Delhi']

d3['is_ut'] = d3['city'].apply(is_ut)
# def is_ut(x):
    
#     # write code below
    
# d3['is_ut'] =

In [81]:
print(d3)

          city  Temperature  is_ut
0   Chandigarh           15  False
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengaluru           24  False
1   Coimbatore           35  False
2    Srirangam           36  False
3  Pondicheery           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT - 
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [85]:
# write function here

def c_to_f(temp_c):
    return (temp_c * 9/5) +32

In [86]:
# check function c_to_f(10)

c_to_f(10)

50.0

In [88]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'

d3['temp_farenhiet'] =  d3['Temperature'].apply(c_to_f)
d3

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15  False            59.0
1        Delhi           22   True            71.6
2       Kanpur           20  False            68.0
3      Chennai           26  False            78.8
4       Manali           -2  False            28.4
0    Bengaluru           24  False            75.2
1   Coimbatore           35  False            95.0
2    Srirangam           36  False            96.8
3  Pondicheery           39   True           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [91]:
d1[d1['city'].isin(['Chandigarh', 'Pondicherry', 'Delhi'])]

         city  Temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [92]:

d1[d1['Temperature'].apply(c_to_f) > 90]

Empty DataFrame
Columns: [city, Temperature]
Index: []

Select only the first three rows of the dataframe d1.

In [93]:
df.head(3)

   points  fruits
e     800  Orange
f     450   Apple
d     400   Mango

Select all the rows and last two columns in the dataframe.

In [95]:
d1.iloc[:,:2]

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

## Groupby

In [97]:
# Create a dataframe using dictionary of your choice

data = pd.DataFrame({
    'city' : ['Telangana', 'Bombay', 'Kashmir', 'Kerala', 'Hyderabad'],
    'Category':['UT', 'UT', 'State', 'State', 'UT'],
    'Sales': [10,20,15,30,5]
})

data

        city Category  Sales
0  Telangana       UT     10
1     Bombay       UT     20
2    Kashmir    State     15
3     Kerala    State     30
4  Hyderabad       UT      5

In [98]:
# Use Groupby of single column with aggregate sum()

data.groupby('city')['Sales'].sum()

city
Bombay       20
Hyderabad     5
Kashmir      15
Kerala       30
Telangana    10
Name: Sales, dtype: int64

In [99]:
# Use Groupby of single column with aggregate count()

data.groupby('Category')['Sales'].count()

Category
State    2
UT       3
Name: Sales, dtype: int64

In [102]:
# Use Groupby of single column with aggregate min() and max()

data.groupby('city')['Sales'].agg(['min', 'max'])

           min  max
city
Bombay      20   20
Hyderabad    5    5
Kashmir     15   15
Kerala      30   30
Telangana   10   10

In [106]:
# Use Groupby of any 2 columns with aggregate mean()

data.groupby(['city', 'Category'])['Sales'].mean()

city       Category
Bombay     UT          20.0
Hyderabad  UT           5.0
Kashmir    State       15.0
Kerala     State       30.0
Telangana  UT          10.0
Name: Sales, dtype: float64

In [107]:
# Use Groupby of any 2 columns with aggregate min() and max()

data.groupby(['city', 'Category'])['Sales'].agg(['min', 'max'])

                    min  max
city      Category
Bombay    UT         20   20
Hyderabad UT          5    5
Kashmir   State      15   15
Kerala    State      30   30
Telangana UT         10   10

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [108]:
a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [109]:
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[us]', length=457, freq='D')

What is the len of a?

In [110]:
print(len(a))

457

What is the type of a?

In [111]:

print(type(a))

<class 'pandas.DatetimeIndex'>